################################################################################
# Copyright 2016 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 0.8.3
# Author: "barzilay" <barzilay@spritecloud.com>
require 'lapis_lazuli'
require 'lapis_lazuli/cucumber'

LapisLazuli::WorldModule::Config.config_file = "config/config.yml"
World(LapisLazuli)

@language = "english"

#TODO: get the remote url dynamically

LapisLazuli.Start do
  browser :remote, {
    :url => "http://selenium__standalone-chrome:4444/wd/hub/",
    :caps => {
      "browser" => "Chrome"
    }
  }
end