################################################################################
# Copyright 2016 spriteCloud B.V. All rights reserved.
# Generated by LapisLazuli, version 0.8.3
# Author: "barzilay" <barzilay@spritecloud.com>

Given(/^I navigate to page (.*) in (.*)$/) do |site, language|
  #Let's set the language globally
  $language = language
  Nav.to(site)
end